version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: dev
    restart: unless-stopped
    container_name: in_good_hands_server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ./:/app
    networks:
      - api

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: dev
    restart: unless-stopped
    depends_on:
      - server
    container_name: in_good_hands_client
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./:/app
    environment:
      - API_URL=http://in_good_hands_server:${SERVER_PORT}
    networks:
      - api
      
networks:
  api:
    name: in_good_hands_api
