services:
  server:
    build:
      target: dev
    volumes:
      - ./:/app
    user: "1000:1000"

  client:
    build:
      target: base
    command: ["yarn", "next", "dev"]
    volumes:
      - ./:/app
    user: "1000:1000"
