version: "3.8"

services:
  db:
    image: "postgres:16.2-alpine3.19"
    restart: unless-stopped
    container_name: in_good_hands_db
    shm_size: 128mb
    volumes:
      - in_good_hands_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - api

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: prod
      args:
        DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    depends_on:
      - db
    container_name: in_good_hands_server
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@in_good_hands_db:5432/postgres?schema=public"
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8000"
    networks:
      - api

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: prod
      args:
        - API_URL=http://in_good_hands_server:${SERVER_PORT}
        - CLIENT_PORT=${CLIENT_PORT}
        - SERVER_PORT=${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      - server
    container_name: in_good_hands_client
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - API_URL=http://in_good_hands_server:${SERVER_PORT}
    networks:
      - api

networks:
  api:
    name: in_good_hands_api

volumes:
  in_good_hands_postgres_data: