services:
  server:
    build:
      target: base
    command: [ "yarn", "vite-node", "-w", "./src/server.ts" ]
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    user: "1000:1000"

  client:
    build:
      target: base
    command: ["yarn", "next", "dev"]
    volumes:
      - ./:/app
    user: "1000:1000"
