FROM node:20.11-alpine3.19 AS base
WORKDIR /app/server

RUN apk add --no-cache libc6-compat

EXPOSE 8000


FROM base as builder

COPY ./server/package.json ./
COPY ./package.json yarn.lock ../
COPY ./share/package.json ../share/

RUN yarn install --frozen-lockfile --ignore-engines --production

COPY ./server/prisma/ ./prisma/

ARG DATABASE_URL

RUN yarn prisma generate

COPY ./share/ ../share/
COPY ./server ./

ENV NODE_ENV production

CMD [ "yarn", "vite-node", "./src/server.ts" ]
