version: "3.8"

services:
  db:
    image: "postgres:16.2-alpine3.19"
    restart: unless-stopped
    hostname: in_good_hands_db
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - api

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    depends_on:
      - db
    hostname: in_good_hands_server
    container_name: in_good_hands_server
    volumes:
      - upload_images:/app/server/upload
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@in_good_hands_db:5432/postgres?schema=public"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - api

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - API_URL=http://in_good_hands_server:8000
    restart: unless-stopped
    depends_on:
      - server
    hostname: in_good_hands_client
    container_name: in_good_hands_client
    environment:
      PORT: ${PORT}
    ports:
      - "${PORT}:3000"
    networks:
      - api

networks:
  api:

volumes:
  postgres_data:
  upload_images: