
fragment AdFragment on AdEntity {
  id
  attributes {
    birthday
    type
    breed
    images {
      data {
          id
          attributes {
            url
          }
      }
    }
    price
    createdAt
  }
}

query Ad($id: ID!) {
  ad(id: $id) {
    data {
      attributes {
        email
        body
        name
        tel
      }
      ...AdFragment
    }
  }
}

query Ads {
  ads {
    data {
      ...AdFragment
    }
  }
}

query AdUpdateData($id: ID!, $ownerId: ID!) {
  ads(filters: {id: {eq: $id}, owner: {id: {eq: $ownerId}}}) {
    data {
      id
      attributes {
        birthday
        type
        body
        breed
        email
        name
        price
        tel
        images {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}

mutation AdUpdate($id: ID!, $data: AdInput!) {
  updateAd(id: $id, data: $data) {
    data {
      id
    }
  }
}
