

query Ads {
    ads {
      data {
        id
        attributes {
          birthday
          type
          breed
          images {
            data {
                id
                attributes {
                  url
                }
            }
          }
          price
          createdAt
        }
      }
    }
}