

query Ads {
    ads {
      data {
          id
          attributes {
            birthday
            type
            body
            breed
            email
            images {
              data {
                  id
                  attributes {
                    url
                  }
              }
            }
            price
            tel
            createdAt
          }
      }
    }
}