fragment User on UsersPermissionsMe {
  id
  username
  email
}


mutation Login($email: String!, $password: String!) {
  login(input: {identifier: $email, password: $password}) {
    jwt
    user {
      ...User
    }
  }
}

mutation Register($email: String!, $password: String!, $username: String!) {
  register (input: {email: $email, password: $password, username: $username}) {
    jwt
    user {
      ...User
    }
  }
}

mutation UpdateCredentials($id: ID!, $data: UsersPermissionsUserInput!) {
  updateUsersPermissionsUser(id: $id, data: $data) {
    data {
      id
    }
  }
}
