query HeroQuery {
    hero {
      data {
        attributes {
          body
          image {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
}